### ISSUE TITLE
Installing Yesod

### ISSUE THREAD

**Issue by DrAlexMV** [tlaitinen/http-attoparsec#1]
It seems that I am unable to install Yesod. The problem, I think, has something to do when going from http-types 8.1 to 8.2 or vice-versa.

Loading package http-attoparsec-0.1.0 ... linking ... ghc: 
lookupSymbol failed in relocateSection (relocate external)
/Users/alexanderventura/Library/Haskell/ghc-7.6.3/lib/http-attoparsec-0.1.0/lib/HShttp-attoparsec-0.1.0.o: unknown symbol `_httpzmtypeszm0zi8zi2_NetworkziHTTPziTypesziHeader_ByteRangeSuffix_con_info'
ghc: unable to load package`http-attoparsec-0.1.0'
Failed to install yesod-core-1.2.4.2

**Comment by tlaitinen** [comment]
Thanks for reporting this issue. For the moment I don't know what is causing it. Which OS are you using?

**Comment by DrAlexMV** [comment]
OSX Mavericks,

I have created an SO as well, though nobody has answered so far:

http://stackoverflow.com/questions/19650477/installing-yesod

If I reinstall http-attoparsec manually using the command

cabal install http-attoparsec --reinstal --force-reinstall

and then I install yesod-core-1.2.4.2, yesod-core-1.2.4.2 installs properly

I am not sure what could be happening.

**Comment by tlaitinen** [comment]
closing due to http://stackoverflow.com/questions/19650477/installing-yesod
